// Generated by CoffeeScript 1.6.3
(function() {
  var registKeywords;

  window.onload = function() {
    var plain_text;
    plain_text = document.documentElement.innerText;
    return registKeywords(plain_text);
  };

  registKeywords = function(plain_text) {
    var content;
    console.log("-----------きてる-------");
    content = new Content(plain_text);
    console.log("content", content);
    return console.log(content.keywords);
  };

}).call(this);
