// Generated by CoffeeScript 1.6.3
(function() {
  this.Content = (function() {
    function Content(plain_text) {
      this.keywords = this.extractKeyword(plain_text);
    }

    Content.prototype.extractKeyword = function(plain_text) {
      var keywords, word, words, _i, _len;
      words = this.extractWords(plain_text);
      keywords = [];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        if (Utils.isKeyword(word)) {
          keywords.push(word);
        }
      }
      return keywords;
    };

    Content.prototype.extractWords = function(plain_text) {
      var segmenter;
      segmenter = new TinySegmenter();
      return segmenter.segment(plain_text);
    };

    return Content;

  })();

}).call(this);
