// Generated by CoffeeScript 1.6.3
(function() {
  var Content;

  Content = (function() {
    function Content(content) {
      extractKeyword;
    }

    Content.prototype.extractKeyword = function(content) {
      var keywords, word, words, _i, _len, _results;
      words = this.extractWords(content);
      keywords = [];
      _results = [];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        if (Utils.isKeyword(word)) {
          _results.push(keywords.push(word));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Content.prototype.extractWords = function(content) {
      var segmenter;
      segmenter = new TinySegmenter();
      return segmenter.segment(content);
    };

    return Content;

  })();

}).call(this);
