// Generated by CoffeeScript 1.6.3
(function() {
  this.HistoryObject = (function() {
    function HistoryObject(data) {
      this.title = data['title'];
      this.content = data['content'];
      this.rect = new Rect(data['rect']);
      this.imageurl = "";
      this.imageaspect = 0;
      this.url = data['url'];
      this.priority = data['priority'];
    }

    return HistoryObject;

  })();

  this.Rect = (function() {
    function Rect(vector4) {
      this.left = vector4[0];
      this.top = vector4[1];
      this.width = vector4[2];
      this.height = vector4[3];
    }

    return Rect;

  })();

}).call(this);
