// Generated by CoffeeScript 1.6.3
(function() {
  this.History = (function() {
    function History() {}

    History.prototype.changeDate = function(date, searchWord) {
      var end, histories, jsonData, start,
        _this = this;
      if (searchWord == null) {
        searchWord = "";
      }
      start = Date.parse(date) - 86400000;
      end = Date.parse(date);
      jsonData = "";
      histories = [];
      return chrome.history.search({
        "text": searchWord,
        "startTime": start,
        "endTime": end,
        "maxResults": 100
      }, function(array) {
        var layout;
        histories = _this.clusteringHistories(array);
        layout = new Layout(histories);
        return layout.drawArticles();
      });
    };

    History.prototype.clusteringHistories = function(array) {
      var clustering;
      clustering = new Clustering(array);
      clustering.clusteringHistories();
      this;
      return this.selectTopHistoryFromEachCluster(clustering);
    };

    History.prototype.selectTopHistoryFromEachCluster = function(clustering) {
      var cluster, histories, i, selectTopFromCluster, selected, _i, _len, _ref;
      selected = [];
      selectTopFromCluster = new SelectTopFromCluster();
      _ref = clustering.clusters;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        cluster = _ref[i];
        histories = clustering.getClusterHistories(i);
        selected[i] = selectTopFromCluster.getTopHistoryFromHistories(histories);
      }
      return selected;
    };

    return History;

  })();

}).call(this);
