// Generated by CoffeeScript 1.6.3
(function() {
  this.HistoryObject = (function() {
    function HistoryObject() {
      this.left = 0;
      this.top = 0;
      this.width = 100;
      this.height = 100;
      this.content = "Hello, World!";
      this.clusterId = 0;
      this.coordinate = {};
      this.word = [];
      this.title = '';
      this.lastVisitTime = 0;
      this.typedCount = 0;
      this.url = '';
      this.visitCount = '';
    }

    return HistoryObject;

  })();

}).call(this);
