// Generated by CoffeeScript 1.6.3
(function() {
  var Rect;

  this.HistoryObject = (function() {
    function HistoryObject() {
      this.title = "";
      this.content = "Hello, World!";
      this.rect = {};
      this.imageurl = "";
      this.imageaspect = 0;
      this.priority;
    }

    return HistoryObject;

  })();

  Rect = (function() {
    function Rect() {}

    Rect.prototype.contructor = function(left, top, width, height) {
      this.left = left;
      this.top = top;
      this.width = width;
      this.height = height;
    };

    return Rect;

  })();

}).call(this);
