// Generated by CoffeeScript 1.6.3
(function() {
  var AspectRatio, ImageRatio, Pattern;

  this.LayoutPattern = (function() {
    function LayoutPattern() {
      this.patterns = [new Pattern(200, new AspectRatio(1.4, 1.6), new ImageRatio(1.0, 0.7)), new Pattern(180, new AspectRatio(1.6, 2.0), new ImageRatio(1.0, 0.4)), new Pattern(100, new AspectRatio(1.8, 2.0), new ImageRatio(0.5, 1)), new Pattern(100, new AspectRatio(1.0, 1.2), null)];
    }

    return LayoutPattern;

  })();

  Pattern = (function() {
    function Pattern() {}

    Pattern.prototype.construnctor = function(minWidth, aspectRatio, imageRatio) {};

    return Pattern;

  })();

  AspectRatio = (function() {
    function AspectRatio(minRatio, maxRaio) {
      this.minRatio = minRatio;
      this.maxRaio = maxRaio;
    }

    return AspectRatio;

  })();

  ImageRatio = (function() {
    function ImageRatio(width, height) {
      this.width = width;
      this.height = height;
    }

    return ImageRatio;

  })();

}).call(this);
