// Generated by CoffeeScript 1.6.3
(function() {
  var plain_text, segmenter, word, words, _i, _len;

  plain_text = document.documentElement.innerText;

  segmenter = new TinySegmenter();

  words = segmenter.segment(plain_text);

  for (_i = 0, _len = words.length; _i < _len; _i++) {
    word = words[_i];
    console.log(isKeyword(word));
  }

}).call(this);
