// Generated by CoffeeScript 1.6.3
(function() {
  var patternType;

  this.isKeyword = function(word) {
    var c, pattern, _i, _len, _ref;
    pattern = [];
    _ref = word.split("");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      c = _ref[_i];
      pattern.push(patternType(c));
    }
    return console.log(pattern);
  };

  patternType = function(c) {
    var key, patterns, re, _i, _len, _ref;
    patterns = {
      "[一二三四五六七八九十百千万億兆]": "M",
      "[一-龠々〆ヵヶ]": "H",
      "[ぁ-ん]": "I",
      "[ァ-ヴーｱ-ﾝﾞｰ]": "K",
      "[a-zA-Zａ-ｚＡ-Ｚ]": "A",
      "[0-9０-９]": "N"
    };
    _ref = Object.keys(patterns);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      re = new RegExp(key);
      if (c.match(re)) {
        return patterns[key];
      }
    }
  };

}).call(this);
