// Generated by CoffeeScript 1.6.3
(function() {
  describe("Clustering", function() {
    beforeEach(function() {
      return this.clustering = new Clustering(histories);
    });
    afterEach(function() {});
    it("TOPキーワードの決定", function() {
      return expect(this.clustering.selectTopKeywords(5)).toEqual(['array', 'Google', '検索', '改行', '削除']);
    });
    return it("キーワードであるかどうかを判定する", function() {
      var target;
      target = "楽しい";
      expect(this.clustering.isKeyword(target)).toBeTruthy();
      target = "あ";
      expect(this.clustering.isKeyword(target)).toBeFalsy();
      target = "今回";
      return expect(this.clustering.isKeyword(target)).toBeFalsy();
    });
  });

}).call(this);
