// Generated by CoffeeScript 1.6.3
(function() {
  describe("Clustering", function() {
    beforeEach(function() {
      return this.clustering = new Clustering(histories);
    });
    it("historiesにキーワード要素を追加", function() {
      this.clustering.setWords2Histories();
      this.clustering.setKeys2Histories();
      expect(this.clustering.histories[0].words).toEqual(['Jasmine', ' ', 'Spec', ' ', 'Runner', ' ', 'v', '2', '.', '0', '.', '0']);
      return expect(this.clustering.histories[0].keywords).toEqual(["Jasmine", "Spec", "Runner"]);
    });
    it("selectTopKeywords: TOPキーワードの決定", function() {
      return expect(this.clustering.selectTopKeywords(5)).toEqual(['JavaScript', 'js', 'Underscore', '配列', 'オブジェクト']);
    });
    return it("isKeyword: キーワードであるかどうかを判定する", function() {
      var target;
      target = "楽しい";
      expect(this.clustering.isKeyword(target)).toBeTruthy();
      target = "あ";
      expect(this.clustering.isKeyword(target)).toBeFalsy();
      target = "今回";
      return expect(this.clustering.isKeyword(target)).toBeFalsy();
    });
  });

}).call(this);
