// Generated by CoffeeScript 1.6.3
(function() {
  describe("Clustering", function() {
    beforeEach(function() {
      return this.clustering = new Clustering(histories);
    });
    afterEach(function() {});
    it("historiesにキーワード要素を追加", function() {
      return this.clustering.addKeys2Histories();
    });
    it("TOPキーワードの決定", function() {
      return expect(this.clustering.selectTopKeywords(5)).toEqual(['JavaScript', 'js', 'Underscore', '配列', 'オブジェクト']);
    });
    return it("キーワードであるかどうかを判定する", function() {
      var target;
      target = "楽しい";
      expect(this.clustering.isKeyword(target)).toBeTruthy();
      target = "あ";
      expect(this.clustering.isKeyword(target)).toBeFalsy();
      target = "今回";
      return expect(this.clustering.isKeyword(target)).toBeFalsy();
    });
  });

}).call(this);
