// Generated by CoffeeScript 1.6.3
(function() {
  describe("HistoryController", function() {
    beforeEach(function() {
      var historyController;
      return historyController = new HistoryController();
    });
    return afterEach(function() {});
  });

}).call(this);
