// Generated by CoffeeScript 1.6.3
(function() {
  describe("SelectTopFromCluster", function() {
    beforeEach(function() {
      var i, _i;
      this.historyobj = [];
      for (i = _i = 0; _i < 10; i = ++_i) {
        this.historyobj[i] = new HistoryObject();
        this.historyobj[i].visitCount = 10 - i;
        this.historyobj[i].url = "http://hoge.com/" + i;
      }
      return this.selectTopFromCluster = new SelectTopFromCluster();
    });
    return it("getTopHistoryFromHistories", function() {
      expect(this.selectTopFromCluster.getTopHistoryFromHistories(this.historyobj).visitCount).toEqual(10);
      return expect(this.selectTopFromCluster.getTopHistoryFromHistories([])).toEqual('');
    });
  });

}).call(this);
