// Generated by CoffeeScript 1.6.3
(function() {
  var SelectTopFromCluster;

  SelectTopFromCluster = (function() {
    function SelectTopFromCluster() {}

    return SelectTopFromCluster;

  })();

}).call(this);
