// Generated by CoffeeScript 1.6.3
(function() {
  chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
    console.log(request);
    if (request.storage) {
      if (typeof request.value !== 'undefined') {
        localStorage[request.strage] = request.value;
      }
      return sendResponse({
        storage: localStorage[request.storage]
      });
    } else {
      return sendResponse({});
    }
  });

}).call(this);
