// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var controller, now;
    controller = new HistoryController();
    console.log(controller);
    now = new Date();
    controller.firstDate();
    controller.changeDate(now);
    return $('#date').on('change', function() {
      var date;
      date = $('#date').val();
      console.log(date);
      if (Date.parse(now) > Date.parse(date)) {
        return controller.changeDate(date);
      } else {
        return console.log("We can't analyze your future.");
      }
    });
  });

}).call(this);
