// Generated by CoffeeScript 1.6.3
(function() {
  this.Cluster = (function() {
    var extractKeyword, isKeyword, patternType;

    function Cluster(histories) {
      this.histories = histories;
    }

    Cluster.prototype.addKeys2History = function() {
      var history, _i, _len, _ref, _results;
      _ref = this.histories;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        history = _ref[_i];
        _results.push(extractKeyword(history.title));
      }
      return _results;
    };

    extractKeyword = function(title) {
      var segmenter, word, words, _i, _len, _results;
      segmenter = new TinySegmenter();
      words = segmenter.segment(title);
      console.log(words);
      _results = [];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        _results.push(isKeyword(word));
      }
      return _results;
    };

    isKeyword = function(word) {
      var c, pattern, _i, _len, _ref, _results;
      pattern = [];
      _ref = word.split("");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        c = _ref[_i];
        _results.push(pattern.push(patternType(c)));
      }
      return _results;
    };

    patternType = function(c) {
      var key, patterns, re, _i, _len, _ref;
      patterns = {
        "[一二三四五六七八九十百千万億兆]": "M",
        "[一-龠々〆ヵヶ]": "H",
        "[ぁ-ん]": "I",
        "[ァ-ヴーｱ-ﾝﾞｰ]": "K",
        "[a-zA-Zａ-ｚＡ-Ｚ]": "A",
        "[0-9０-９]": "N"
      };
      _ref = Object.keys(patterns);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        key = _ref[_i];
        re = new RegExp(key);
        if (c.match(re)) {
          return patterns[key];
        }
      }
    };

    return Cluster;

  })();

}).call(this);
