// Generated by CoffeeScript 1.6.3
(function() {
  this.Cluster = (function() {
    function Cluster(histories) {
      console.log("Cluster");
      this.histories = histories;
    }

    Cluster.prototype.print_title = function() {
      return console.log(this.histories);
    };

    return Cluster;

  })();

}).call(this);
