// Generated by CoffeeScript 1.6.3
(function() {
  this.headerHeight = 38;

  this.sidebarWidth = 300;

  $(function() {
    var mainHeight, newstext;
    mainHeight = $(window).height() - headerHeight;
    $("#main-container").css("height", mainHeight);
    $("#sidebar").css("height", mainHeight);
    newstext = $(".news-text").html();
    return console.log(newstext);
  });

}).call(this);
